version: '3'

networks:
  air_miles_card:
    driver: bridge

services:
  air_miles_card_db:
    image: postgres:14
    container_name: air_miles_card_db
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD==root
      - POSTGRES_DB=air_miles_card
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/docker/postgresql:/var/lib/postgresql/data/pgdata
    networks:
      - air_miles_card
    ports:
      - "5432:5432"

  air_miles_card_redis:
    image: docker.io/bitnami/redis:6.2
    container_name: air_miles_card_redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=root
    volumes:
      - '/var/docker/redis:/bitnami/redis/data'
    networks:
      - air_miles_card
    ports:
      - '6379:6379'

  air_miles_card_node:
    build: .
    container_name: air_miles_card_node
    entrypoint: dockerize -wait tcp://air_miles_card_db:5432 -timeout 20s yarn start
    tty: true
    restart: always
    networks:
      - air_miles_card
    depends_on:
      - air_miles_card_db
      - air_miles_card_redis
    ports:
      - '3333:3333'
