version: '3'

networks:
  customers_core:
    driver: bridge

services:
  customers_core_db:
    image: docker.io/bitnami/postgresql:14
    container_name: customers_core_db
    restart: always
    tty: true
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD==root
      - POSTGRESQL_DB=customers_core
    volumes:
      - /var/docker/postgresql:/bitnami/postgresql
    networks:
      - customers_core
    ports:
      - "5432:5432"

  customers_core_redis:
    image: docker.io/bitnami/redis:6.2
    container_name: customers_core_redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=root
    volumes:
      - '/var/docker/redis:/bitnami/redis/data'
    networks:
      - customers_core
    ports:
      - '6379:6379'

  customers_core_node:
    build: .
    container_name: customers_core_node
    entrypoint: dockerize -wait tcp://customers_core_db:5432 -timeout 20s yarn start
    tty: true
    restart: always
    networks:
      - customers_core
    depends_on:
      - customers_core_db
      - customers_core_redis
    ports:
      - '3333:3333'

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   container_name: customers_core_nginx
  #   networks:
  #     - customers_core
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - customers_core_node

